afrikaans <- "Die borsstuk bestaan uit vier segmente, waarvan die agterste een in werklikheid 'n agterlyfsegment is, maar in die borsstuk geleë is. By koninginne en mannetjies kom een paar vlerke aan die tweede en derde borssegment voor, maar werkers en soldate het geen vlerke nie. Wat dikte en beharing betref verskil die liggaamswand van spesie tot spesie. Sommige spesies het yl, lang hare wat regop staan of teen die liggaam lê."

albanian <- "Shqipja, si gjuhë moderne, përfaqëson një degë më vete në familjen e gjuhëve indo-evropiane. Shkruhet me shkronja latine. Gjuha shqipe përfshin gjuhën standarde ose gjuhën e njësuar letrare shqipe, e cila u miratua në Kongresin e Drejtshkrimit të Shqipes në vitin 1972 në Tiranë, dhe të gjitha dialektet, nëndialektet e të folurat që fliten nga shqiptarët. Gjuha shqipe ka dy dialekte kryesore: gegërishten, toskërishten, dhe një kronolekt."

amharic <- "ኢትዮጵያ ተፈጥሮ ያደላት ሀገር ናት። ከአፍሪካ ትላልቅ ተራራዎች እንዲሁም ከዓለም ከባህር ጠለል በታች በጣም ጥልቅ ከሆኑ ቦታዎች አንዳንዶቹ ይገኙባታል። ሶፍ ዑመር ከአፍሪካ ዋሻዎች ትልቁ ሲሆን ፣ ዳሎል ከዓለም በጣም ሙቅ ቦታዎች አንዱ ነው። ወደ ሰማንኒያ የሚቆጠሩ ብሔሮችና ብሔረሰቦች ዛሬ በኢትዮጵያ ይገኛሉ። ከእነዚህም ኦሮሞና አምሀራ በብዛት ትልቆቹ ናቸው። ኢትዮጵያ በኣክሱም ሓውልት፣ ከአንድ ድንጋይ ተፈልፍለው በተሰሩ ቤተ-ክርስትያኖቹዋ እና በኦሎምፒክ የወርቅ ሜዳልያ አሸናፊ አትሌቶቹዋ ትታወቃለች። የቡና ፍሬ ለመጀመሪያ ጊዜ የተገኘው በኢትዮጵያ ሲሆን ሀገሪቱዋ በቡናና ማር አምራችነት በአፍሪካ ቅድሚያ ይዛለች። "

arabic <- " أما الأسماء الأخرى للأردن فقد كانت تسمى على اسم الممالك التي كانت تسكنها، والاسم الخاص هو المناطق الجغرافية وهي مكونات البلاد التي قامت بها هذه الممالك، وسمِّيت كل مملكة وشعبها باسم تلك المنطقة مثل الأدوميون (نسبة إلى أدوم) والمؤابيون (نسبة إلى مؤاب)، والحشبونيين (نسبة إلى حشبون ـ حسبان الحالية)، والعمونيون (نسبة إلى ربة عمون ـ عمان الحالية). والباشانيون (نسبة إلى باشان وهي بيسان الحالية). ومملكة الأنباط نسبة إلى اسمهم وليس إلى اسم المكان. فقد جاءت هذه القبائل العربية مهاجرة من جزيرة العرب وحطّت رحالها في أرض الأردن واستوطنت كل واحدة منها دياراً يفصلها عن الأخرى معالم طبيعية وكانت العلاقة بينهم ودية، وكانت هذه"

armenian <- "Նախնադարյան հասարակության հին քարի դարի առաջին ենթափուլը՝ ստորին պալեոլիթը, Հայաստանի տարածքում սկսվել է մոտ 2 միլիոն տարի առաջ և ավարտվել է մոտ 100 000 տարի առաջ։ Հայկական լեռնաշխարհում հայտնի են այս ժամանակաշրջանի մի քանի բացօթյա հնավայրեր, կայաններ և քարայրային տիպի հուշարձաններ։ Դրանցից հայտնի է Գուգարքում հայտնաբերված հին քարեդարյան կայանը, որի տարիքը մոտ 1, 8 միլիոն տարի է։"

basque <- "Badu arrazoirik euskal izena hartzeko, lurralde hori baita bere eremu osoan sorreratik bertatik euskara hizkuntza ofizialtzat duen lurralde bakarra. Gaztelania ere bada ofiziala. Nafarroako Foru Erkidegoari EAEren parte izateko eskubidea onartu zaio Espainiako Konstituzioan, baina hegoaldeko nafar herritarrek horri buruz erabakitzeko duten eskubidea ez da inoiz erreferendum batean gauzatu."

belarusian <- "Унітарная дзяржава, прэзідэнцкая рэспубліка. 20 ліпеня 1994 гады пасаду прэзідэнта заняў Аляксандр Лукашэнка, які перамагаў таксама на выбарах 2001, 2006, 2010 і 2015 гадоў. 23 верасня 2020 года, пасля фальсіфікацыі прэзідэнцкіх выбараў, Аляксандр Лукашэнка на таемнай інаўгурацыі ізноў абвясціў сябе прэзідэнтам. Пасада прэзідэнта Беларусі застаецца нявызначанай."

bosnian <- "Butmirska kultura jest kultura mlađeg neolita koja se rasprostirala na teritoriji današnje srednje Bosne, između Zavidovića i Sarajeva. Ime je dobila po prahistorijskom naselju u Butmiru u općini Ilidža, koje je najstarije i najpoznatije arheološko nalazište u Bosni i Hercegovini iz kasnog kamenog doba. Ostali važniji lokaliteti Butmirske kulture jesu Okolište, Nebo i Obre."

breton <- "Daoust d'ar frankiz kollet ha d'ar frammoù melestradurel a zisrann ar Vretoned e kendalc'h Breizh da vevañ evel un unanenn vroadel. Ar merkoù anatañ eus kement-se eo he sevenadur dibar (sonerezh, kan, lennegezh, keginerezh, dañsoù, c'hoariva, gizioù emwiskañ hag all), he yezhoù (ar brezhoneg hag ar gallaoueg), hec'h armerzh (gant luskadoù evel Produet e Breizh)."

bulgarian <- "Към петото хилядолетие преди н.е. в североизточна България процъфтява култура, която създава най-ранните златни украшения в Европа. От античността до Тъмните векове по земите на днешна България се развиват културите на траките, древните гърци, келтите, готите и римляните. С пристигането на славяните през VI век, а век по-късно и на прабългарите, започва процесът на изграждане на българската държавност."

catalan <- "El territori que ocupa Catalunya fou conquerit per l'Imperi Romà el 218 aC i formà part de la província Tarraconense; al segle v la Tarraconense fou conquerida pels gots i formà part del Regne de Toledo. El 712 els musulmans derrotaren els gots i ocuparen la Tarraconense, però a finals d'aquell mateix segle en foren expulsats de la part nord pels francs amb el suport de Carlemany."

chinese <- "周恩来为组长的第三小组在起草中国人民政治协商会议共同纲领时，考虑到应照顾人民的传统和习惯，于是新政治协商会议筹备会会议第一次全体会议上通过的中华人民民主共和国政府组织大纲草案注明了：中华人民民主共和国简称中华民国。后来周恩来表示：中华民国叫了38年，一下子换了，会使落后的政治水准很低的人不能接受。所以，我们许可简称中华民国，但这个中华民国的性质与过去是有区别的，它不包括地主官僚资产阶级在内。"

croatian <- "Ljudi mlađeg kamenog doba na prostoru Hrvatske su živjeli u plodnim nizinama rijeka i uz Jadransko more. Prema prostoru najvažnijih nalazišta razlikujemo četiri kulture. Starčevačka kultura se prostirala dijelom sjeverne Hrvatske, a nositelji su ratari i stočari koji su živjeli u sojenicama i proizvodili keramiku koju su bojali crvenom bojom. Sopotska kultura prostirala se na prostoru Slavonije."

czech <- "Míra nezaměstnanosti je dlouhodobě nízká a pod průměrem vyspělých zemí. V indexu ekologické stopy je Česko oproti některým jiným vyspělým zemím menším ekologickým dlužníkem. Podle, který vypracovává každoročně Institute for Economics and Peace, se Česko dlouhodobě řadí mezi 15 nejbezpečnějších zemí (pohybuje se mezi 5. a 15. místem) na světě (index zohledňuje hrozbu válečného konfliktu i úroveň vnitřní násilné kriminality)."

danish <- "Den danske historie indledes i det 8. århundrede, hvor de skriftlige kilder begynder at omtale forholdene her. Den nordiske regions forhistoriske tid, og såvel den efterfølgende vikingetid, omtales også, selv af historikerne, som oldtid. Her begynder de nordfra-kommende (danske, svenske og norske) vikinger at hærge og handle i det meste af Europa."

dutch <- "Den Haag speelt een belangrijke internationale rol op juridisch gebied, als locatie voor vier internationale tribunalen en Europol. In 2009 behoorde Nederland als 's werelds zevende economie naar bbp per hoofd van de bevolking tot de meest ontwikkelde landen. Het bezette in 2013 de vierde plaats in de index van de menselijke ontwikkeling."

english <- "During the settlement period the lands ruled by the incomers seem to have been fragmented into numerous tribal territories, but by the 7th century, when substantial evidence of the situation again becomes available, these had coalesced into roughly a dozen kingdoms including Northumbria, Mercia, Wessex, East Anglia, Essex, Kent and Sussex. Over the following centuries, this process of political consolidation continued."

esperanto <- "La vortprovizo de Esperanto devenas plejparte el la okcidenteŭropaj lingvoj, dum ĝia sintakso kaj morfologio montras ankaŭ slavlingvan influon. La morfemoj ne ŝanĝiĝas kaj oni povas ilin preskaŭ senlime kombini, kreante diverssignifajn vortojn, Esperanto do havas multajn kunaĵojn kun la analizaj lingvoj, al kiuj apartenas ekzemple la ĉina kaj la angla."

estonian <- "Eesti haldusjaotus on välja kujunenud sajandite jooksul ja seda on aeg-ajalt kohandatud aja nõuetest tulenevatele vajadustele. Enamik praegusi maakondi olid moodustatud juba 18. sajandil. 20. sajandi esimesel poolel loodi kaks uut maakonda, Valgamaa ja Petserimaa. Eesti oli enne teist maailmasõda jagatud 11 maakonnaks: Lääne-, Harju-, Järva-, Viru-, Pärnu-, Viljandi-, Tartu-, Valga-, Võru-, Petseri- ja Saaremaaks."

finnish <- "Yleisin kivennäismaalaji on moreeni, jonka päälle on paikoin kasautunut savikkoa. Eloperäisistä maalajeista soille on muodostunut turvetta ja kangasmetsiin kangashumusta. Viimeisen jääkauden lopulla syntyneet jäätikön reunan suuntaiset reunamuodostumat ja liikesuunnan mukaiset harjut ovat Suomelle tunnusomaisia maastonmuotoja. Reunamuodostumista merkittävimmät ovat Salpausselät."

french <- "Les âges plus ou moins anciens des épisodes volcaniques qui ont provoqué leur formation expliquent des degrés divers d'érosion des reliefs, de subsidences, de formations de récifs coralliens et de dépôts calcaires. De ce fait, plusieurs de ces îles conservent un reliquat rocheux plus ou moins élevé des anciens volcans."

frisian <- "De Fryske fêstewâl wurdt yn it easten en it suden troch lân omsletten. Yn it easten troch de provinsjes Grinslân en Drinte, en yn it suden troch Oerisel en de Noardeastpolder. De Ofslútdyk ferbynt West-Fryslân yn Noard-Hollân mei de Fryske fêstewâl by it plak Surch en is de skieding tusken de Iselmar en de Waadsee. De Iselmar leit westlik/súdwestlik fan de Fryske fêstewâl en oan de west- en noardkante leit de Waadsee."

georgian <- "თანამედროვე საქართველოს ტერიტორია მუდმივად დასახლებული იყო ადრეული ქვის ხანიდან მოყოლებული. კლასიკურ ანტიკურ ხანაში აყვავდა ადრეული ქართული სახელმწიფოები კოლხეთი და იბერია, რამაც დასაბამი მისცა საერთო ქართულ კულტურასა და სახელმწიფოებრიობას. ქრისტიანობა გაბატონდა ადრეული IV საუკუნიდან; ქვეყანა გაერთიანებული მონარქია გახდა 1008 წელს."

german <- "Daneben gibt es Regional- und Minderheitensprachen und Migranten mit anderen Muttersprachen; bedeutendste Zweitsprache ist Englisch. Die Kultur Deutschlands ist vielfältig und wird neben zahlreichen Traditionen, Institutionen und Veranstaltungen beispielsweise in der Auszeichnung als Welterbe in Deutschland, in Kulturdenkmälern und als immaterielles Kulturerbe erfasst und gewürdigt."

greek <- "Μετά την εμφάνιση του ελληνικού εθνικού κινήματος, το 1821 ξέσπασε επανάσταση των Ελλήνων εναντίον της Οθωμανικής Αυτοκρατορίας με σκοπό την ίδρυση ανεξάρτητου κράτους, το οποίο αναγνωρίστηκε το 1830. Τον επόμενο αιώνα το Βασίλειο της Ελλάδας επεκτάθηκε εδαφικά, κυρίως με τους Βαλκανικούς Πολέμους, ως την αποτυχία της Μικρασιατικής εκστρατείας το 1922."

hebrew <- "התוכנית התקבלה על ידי הסוכנות היהודית, אך נדחתה בידי ההנהגה הערבית; עימות צבאי שניצת בין הצדדים התפתח למלחמת העצמאות, שבמהלכה הוכרזה הקמתה של מדינת ישראל. בתום המלחמה והסכמי שביתת הנשק, שלטה ישראל במרבית שטח המנדט לשעבר, אף מעבר למה שהוקצה למדינה היהודית בתוכנית החלוקה. יהודה ושומרון ורצועת עזה נכבשו על ידי ירדן ומצרים, בהתאמה. המדינה הערבית לא הוקמה, ומאות אלפי ערבים־פלסטינים נסו או גורשו מבתיהם במסגרת הנכבה."

hindi <- "बीसवी सदी के प्रारम्भ में आधुनिक शिक्षा के प्रसार और विश्वपटल पर बदलती राजनीतिक परिस्थितियों के चलते भारत में एक बौद्धिक आन्दोलन का सूत्रपात हुआ जिसने सामाजिक और राजनीतिक स्तरों पर अनेक परिवर्तनों एवम आन्दोलनों की नीव रखी। १८८५ में भारतीय राष्ट्रीय कांग्रेस की स्थापना ने स्वतन्त्रता आन्दोलन को एक गतिमान स्वरूप दिया। बीसवीं शताब्दी के प्रारंभ में लम्बे समय तक स्वतंत्रता प्राप्ति के लिये विशाल अहिंसावादी संघर्ष चला."

hungarian <- "Az Alföld egy feltöltött síkság, területén szinte nincs szintkülönbség, a legnépesebb városa Debrecen. A Kisalföld az ország északnyugati részén fekszik, a Szigetköz, a Rábaköz és a Marcal-medence alkotják, legnépesebb városa Győr. Az Alpokalja a nyugati határ mentén helyezkedik el, a Keleti-Alpok lejtővidéke az ország legcsapadékosabb része, legmagasabb területei a Kőszegi-hegység és a Soproni-hegység."

icelandic <- "Flestir landsnámsmanna voru ásatrúar þó nokkrir kristnir og höfðu þeir flestir kynnst kristinni trú og látið skírast á Bretlandseyjum. Um svipað leyti sendi Haraldur blátönn Danakonungur saxneskan biskup til Íslands til kristniboðs. Ekki gekk það alltaf og komu fleiri kristniboðar hingað á næstu árum og varð þeim nokkuð ágengt. Ólafur Tryggvason Noregskonungur var mjög áhugasamur um að kristna Ísland — með góðu eða illu."

indonesian <- "Hingga tahun 75000 Sebelum Masehi, daratan Nusantara bagian barat (kira-kira kepulauan sebelah barat termasuk Sumatra, Jawa, dan Kalimantan sekarang) masih menyatu dengan daratan utama Asia. Pada abad ini pula terjadi erupsi Gunung Toba, yang disebut-sebut sebagai salah satu letusan gunung api terbesar sepanjang sejarah yang menyebabkan perubahan iklim yang dikatakan hampir memusnahkan populasi manusia modern saat itu."

irish <- "Le linn tréimhse na hoighearaoise deireanaí agus go dtí thart ar 10,000 RCh, clúdaíodh oighir go tréimhsiúil formhór na hÉireann. Bhí leibhéil na farraige níos ísle agus bhí Éire, cosúil leis an mBreatain Mhór, mar chuid de mhór-roinn na hEorpa. Faoi 16,000 RC, ba chúis le hardú na farraige de bharr leá oighir Éire a bheith scartha ón mBreatain Mhór. Níos déanaí, timpeall 6000 RCh, scaradh an Bhreatain Mhór ó mhór-roinn na hEorpa."

italian <- "La rivoluzione neolitica non modificò eccessivamente la vita degli abitanti in grotta dell'Italia meridionale costiera che continuarono a basare la propria sussistenza sulla caccia e la raccolta di molluschi. A partire dal VI millennio a.C. però queste popolazioni, come ad esempio quelle della grotta dell'Uzzo, si stabilirono nelle pianure circostanti dando vita alla cultura di Stentinello che realizzò i primi villaggi difesi da fossati."

japanese <- "環太平洋パートナーシップに関する包括的及び先進的な協定を推進するなど、概ね自由貿易体制を支持している。現代日本社会は少子化が進んでおり、超高齢社会であるとされる。人口変化は明治以来初めて2010年頃から緩やかになっている。また、従来の中間層が貧困化し、格差社会にもなっている。21世紀に入ってからはアメリカや中国に押されつつあるもののエレクトロニクス産業や自動車産業の中心地であり、トヨタ、日産、ホンダ、東芝、ソニー、パナソニック、日立製作所など多数の大企業を輩出し、科学技術のリーダーとされる。"

korean <- "한국은 동아시아의 한반도에 위치하고 있다. 북서쪽으로는 압록강을 경계로 중국과 경계를 이루고, 북동쪽으로는 두만강을 경계로 중국 및 러시아와 마주하고 있다. 삼면이 바다인 한국에는 서쪽으로 황해(서해), 동쪽으로 동해, 남쪽으로 남해에 의해 둘러싸여 있다. 한반도 및 부속도서의 최북단은 함경북도의 온성, 최서단은 평안북도의 마안도, 최동단은 경상북도 울릉군에 속한 섬 독도, 최남단은 마라도이다. 한반도의 동부 및 북부는 비교적 높은 산들로 이루어진 산지 지형을 특징으로 하고."

latin <- "In nonnullis linguis novis, titulus imperatoris nominat solum unum, qui magnum regnum gubernat, sed res publica Romana multos habuerat imperatores ante Octavianum, qui ad tempus et eodem tempore imperio usi sunt: Imperium habuerunt consules et praetores, quorum in provinciis copiae fuerunt, simul cum aliis. Octavius, divite sed non nobilissime gente anno 63 a.C.n. orto, quod a Gaio Iulio Caesare in filium adoptatus est."

latvian <- "Atskaitot īsu vācu okupācijas periodu Otrā pasaules kara laikā, Latvija palika Padomju Savienības okupēta līdz Dziesmotās revolūcijas noslēgumam, kad 1990. gada 4. maijā tika pasludināta neatkarības atjaunošana, ko 1991. gada 6. septembrī atzina PSRS. Pēc PSRS sabrukuma Krievijas Federācija līdz 1994. gadam izveda no Latvijas savus bruņotos spēkus. Latvijas Republika atjaunoja politisko un ekonomisko sadarbību ar Rietumu valstīm un 2004."

lithuanian <- "Daugėjant iš plėšiamųjų žygių parsivežamo turto ir belaisvių ryškėjo turtiniai skirtumai, išsiskyrė karingieji kunigaikščiai iš kitų perimdami valdžią. Lietuvos teritorijoje gyvavusių kelių skirtingų baltų genčių sukurtų kunigaikštysčių jungimasis į vieną konfederacinę ar federacinę Lietuvos valstybę prasidėjo greičiausiai dar I-ame tūkstantmetyje, tačiau anot vyraujančios istoriografinės sampratos valstybės susidarymas baigėsi."

malay <- "Negeri Sabah dibahagi oleh Banjaran Crocker di mana terletaknya Gunung Kinabalu iaitu gunung tertinggi di Malaysia pada 4,095.2 meter (13,436 kaki). Gunung ini yang terletak di Taman Negara Kinabalu mendapat pengiktirafan sebagai Tapak Warisan Dunia UNESCO. Malaysia mempunyai iklim khatulistiwa yang dicirikan oleh monsun tahunan barat daya (April hingga Oktober) dan timur laut (Oktober hingga Februari)."

manx <- "Va sleih cummal ayns Mannin roish y vlein 6500 RC, as haink cultoor Gaelgagh ayns yn 5oo lhing BNJ as veih shen haink Gaelg Vanninagh. Voish mysh BNJ 850, haink Mannin dy ve ny sheshaght Gaelgagh-Loghlynagh, kyndagh rish Loghlynee garraghey dys yn Ellan. Lurg lhing jeh reiltys neuchinjagh, eddyr reeaghyn Nalbin as Hostyn, haink Mannin dy ve fo çhiarnys Chrooin Hostyn ayns 1765 liorish yn Slattys Aa-Ghreim."

marathi <- "भारत देश हा मानवी इतिहासातील प्राचीन देशांमध्ये गणला जातो. मध्यप्रदेशातील भीमबेटका येथील पाषाणयुगातील भित्तीचित्रे भारताच्या मानवी अस्तित्वाचे सर्वांत जुन्या पुराव्यांपैकी आहेत. पुराणतज्ञांनुसार, सत्तर हजार वर्षांपूर्वी आदिमानवाने भारतात प्रवेश केला. साधारणपणे ९००० वर्षांपूर्वी भारतात ग्रामीण व शहरी स्वरूपांची मानवी वस्ती होऊ लागली व त्याचेच हळूहळू सिंधू संस्कृतीमध्ये. "

nepali <- "नेपालको एकीकरण हुनुभन्दा अघि काठमाडौँ उपत्यकालाई नेपाल भनेर चिनिन्थ्यो। नेपाल शब्दको वास्तविक उत्पत्ति अनिश्चित छ। नेपाल शब्द चौथो शताब्दी इसापूर्वमा पुरानो भारतीय साहित्यिक ग्रन्थहरूमा देखा परेको थियो। सबैभन्दा पुरानो ग्रन्थहरूमा अज्ञात योगदानहरू भएको मानिन्छ जुन प्रारम्भिक आधुनिक अवधि भन्दा अगाडि हो। तथापि, यसले एक पूर्ण कालक्रम स्थापना गर्न सक्दैन। इतिहासमा पूर्ण चित्रको अभाव, भाषाविज्ञान वा सान्दर्भिक भारोपेली र भोट-बर्मेली भाषाहरूको अपर्याप्त ज्ञानको अभावले एक व्यावहारिक सिद्धान्त प्रदान गर्ने शैक्षिक प्रयासहरू यसमा बाधक बनेका छन्।"

norwegian <- "Norges hovedland utgjør sammen med Sverige og deler av Finland Den skandinaviske halvøya, og grenser også mot Russland. Landet er langt og smalt. Kysten strekker seg langs Nord-Atlanteren i nesten hele sin lengde. Tre havområder utgjør kystlinjen: Nordsjøen og dens avstikker Skagerrak i sørvest og sør, Norskehavet i vest og Barentshavet i nordøst. Til havs har Norge delelinjer med Sverige, Danmark, Storbritannia, Færøyene, Island, Grønland og Russland."

persian <- "با پدیداری صفویان، رونق اقتصادی و پایداری مرزها نمود بیشتری یافت و ایران پس از حدود ۹ سده، تحت یک حکومت مستقل بومی، متحد شد و مذهب آن به شیعه تغییر یافت. پس از سرنگونی صفویان،های افشاریان و زندیان به ترتیب بر ایران، فرمان راندند. در دوران قاجاریان،هایی با روسیه انجام شد که سهی قابل توجهی را از این کشور جدا کرد. در دههٔ ۱۲۸۰، جنبش مشروطهٔ ایران قدرت گرفت و قانون اساسی مشروطه را بر این کشور، حاکم کرد. در سال ۱۳۰۴، شاهنشاهی پهلوی توسط رضاشاه بنیان نهاده شد؛ این دوران با اصلاحات گسترده و ایجاد زیرساخت نوین برای ایران، همراه شد. در دوران محمدرضا پهلوی نیز اصلاحات ادامه یافت و ایران، رشد اقتصادی سریعی را تجربه کرد؛"

polish <- "Wydarzeniem, które stanowiło pierwszy krok na drodze ku powstaniu państwa polskiego, było objęcie władzy nad plemieniem Polan przez ród Piastów. Nastąpiło to w nieznanych okolicznościach i czasie, najprawdopodobniej jednak w drugiej połowie IX wieku. Główny ośrodek państwa Polan stanowiło Gniezno. Pierwszym historycznym władcą piastowskim był natomiast książę Mieszko I, chociaż późniejszy (XII w.) kronikarz Gall Anonim podaje także imiona jego przodków."

portuguese <- "A população ameríndia era repartida em grandes nações indígenas compostas por vários grupos étnicos entre os quais se destacam os grandes grupos tupi-guarani, macro-jê e aruaque. Os primeiros eram subdivididos em guaranis, tupiniquins e tupinambás, entre inúmeros outros. Os tupis se espalhavam do atual Rio Grande do Sul ao Rio Grande do Norte de hoje, sendo a primeira raça indígena que teve contato com o colonizador e decorrentemente a de maior presença."

quechua <- "Qusqu, Inkakunap uma llaqtanñas ñawpa pachañas Qusqu qhapaq suyu pachañas tawantin llaqta suyuyuqsi karqan. Chaypacha Hanan Qusqu, Urin Qusqu suyus karqan, chay iskay suyutaq iskaymansi rakisqa karqan, tawantin suyus. 1438 watapi Pachakutiq Inka Yupanki Chanka runakunata atipaspa hatunkaray suyuta hap'iptinsi, Inkakunap atiynin, mama llaqtan anchata mast'arikurqansi. Ñawpa pacha hina, manas qhapaq llaqtallapichu, ichataq tukuy atipasqan suyuntinpis tawantin rakin kamarirqanku."

romanian <- "După desființarea iobăgiei în 1746, cuvântul rumân a căzut treptat din uz și ortografia s-a stabilizat la forma de român. Tudor Vladimirescu, lider revoluționar de la începutul secolului al XIX-lea, a folosit termenul Rumania să se refere exclusiv la principatul Țării Românești, Valahia. Din termenul rumân s-a format la finele secolului XVIII exonimul modern a poporului român și a statului român în cazul principalelor limbi europene."

rumantsch <- "L’identitad e la coesiun naziunala na sa basan betg sin ina lingua, etnia u religiun communabla, mabain sin facturs interculturals sco la cretta en la democrazia directa, in aut grad d’autodeterminaziun locala e regiunala e la cultura exprimida da chattar cumpromiss en la procedura da decisiun politica. En quest reguard vegn la Svizra savens considerada sco exempel per auters stadis."

russian <- "В строении Урало-Монгольского эпипалеозойского складчатого пояса, разделяющего 2 древние платформы, выделяются области рифейской, байкальской, салаирской, каледонской и герцинской складчатости. Енисей-Саяно-Байкальская область рифейской и байкальской складчатости обрамляет Сибирскую платформу. Вдоль границы с Восточно-Европейской платформой располагается Предуральский краевой прогиб, заполненный пермскими толщами с месторождениями каменного угля на севере и калийных солей в средней части прогиба."

sanskrit <- "भारतस्य अर्थव्यवस्था विश्वे पंचमे स्थाने प्राप्नोति । अधुना एषः देशः अभिवृद्धिपथे प्रचलदस्ति । एषः अण्वस्त्रयुतः देशः अस्ति । प्रादेशिकस्तरे शक्तिमान् देशः । विश्वे एव सेनाबले तृतीयं स्थानमस्ति अस्य । सेनायाः कृते व्ययविषये अस्य दशमं स्थानमस्ति । भारतं गणतन्त्रात्मकं देशमस्ति । भारतीयसंसदे सदनद्वयमस्ति । अत्र २८ राज्यानि, सप्तकेन्द्रशासितप्रदेशाः च सन्ति । एतत् आर्थिकपुरोगामिपञ्चराष्ट्रेषु अयमपि अनयतमः देशः ।"

scots <- "Scotland wis ance a free kinrick, but syne gaed intil a union wi England in 1603, whan Jeams VI o Scotland becam Jeams I o England efter the deith o Elspeth I. This union wis makkit formal on 1 Mey 1707 bi the Treaty o Union. The Scots Pairlament wis gotten rid o on 26 Mairch. The union southert baith kinricks, makkin the Kinrick o Great Breetain, wi a new single Pairlament haudden in Wastmeenster, Lunnon, but some pairts o Scotland's institutions."

scotsGaelic <- "Cha tàinig na pàirtean mu thuath agus mu dheas na Breatainn teannta, no còmhla, gu 75 muillean bliadhnan roimh toiseach na Bholcanas ann an Lodaidh an Ear. Bha Alba agus pàirt de cheann a tuath na Sasainn nam pàirt de thìr-mòr Laurentian ro -làimh, far an robh Aimearaga mu Thuath agus a’ Ghraonlainn. Aig a h-aon àm, bha an dara leth de 'n Bhreatainn torr nas fhada (mu 40 de domhainn leud) do 'n dheas, faisg air Afraga agus Aimearaga mu Dheas ann an tìr-mòr de."

serbian <- "Биогеографски, на територији Србије налазе се две зоналне вегетације (односно, два биома) — већи део површине припада биому широколисних и мешовитих шума умерених предела, док предели изнад горње шумске границе припадају биому тундри (алпијске тундре). У оквиру шумског биома присутна су четири екорегиона: балканске мешовите шуме (заузимају највећи део територије јужно од Саве и Дунава), панонске мешовите шуме."

slovak <- "Prvé známky o osídlení Slovenska pochádzajú z konca paleolitu približne spred 250 tis. rokov. O rozkvete ľudských spoločností na území Slovenska svedčí mnoho archeologických pamiatok ako napríklad nález lebky neandertálca v Gánovciach. Bohatšie doklady o živote prehistorických ľudí sa vzťahujú k neolitu. Našli sa zvyšky ich obydlí, keramiky, ale aj ich duchovného života vo forme obetných darov alebo kultových predmetov akými boli pravdepodobne aj venuše z Nitrianskeho Hrádku, Moravian nad Váhom a ďalších miest."

slovenian <- "Slovenija ima zaradi lege v zmernih geografskih širinah na prehodu Alp v Dinaride in Sredozemlja v Panonsko kotlino izrazito prehodno podnebje, ki je posledica sovplivanja morskih in celinskih zračnih gmot. Na lokalne podnebne razmere ima precejšen vpliv tudi velika reliefna pestrost in višinska razčlenjenost površja. Na slovenskem ozemlju prihaja do stika in prepletanja gorskega (alpskega), sredozemskega in celinskega podnebja."

spanish <- "Aparte de la teoría de origen fenicio, que es la más aceptada a pesar de que el significado preciso del término sigue siendo objeto de discusiones, a lo largo de la historia se propusieron diversas hipótesis, basadas en similitudes aparentes y significados más o menos relacionados. A principios de la Edad Moderna, Antonio de Nebrija, en la línea de Isidoro de Sevilla, propuso su origen autóctono como deformación de la palabra ibérica Hispalis."

swahili <- "Pia ina mito mingi ambayo inaelekeza maji yake katika Bahari ya Hindi mashariki mwa nchi, lakini mingine inachangia Mto Zambezi kupitia Ziwa Nyasa, michache Bahari ya Kati kupitia Ziwa Victoria na mto Naili, mingine tena Bahari Atlantiki kupitia Ziwa Tanganyika na mingine inaishia katika mabonde kama ya Ziwa Rukwa. Tabia ya nchi ya Tanzania hubadilika kwa nyakati tofautitofauti katika mwaka. Hivyo kiasi cha mvua na halijoto husababisha tofauti za aina ya uoto wa asili, udongo na aina ya mazao yanayolimwa."

swedish <- "Järnet blev den huvudsakliga redskapsmetallen omkring 400–500 f.Kr. Det första skriftspråket, runorna, introducerades troligen under 300-talet e.Kr. men förefaller främst haft en magisk funktion. Först omkring år 800 började runor användas oftare som kommunikationsmedel. Ungefär samtidigt började de första spåren av en fastare samhällsorganisation att dyka upp. När Sverige kristnandes och i vilken omfattning är oklart."

tagalog <- "Naging bahagi ang Pilipinas sa Imperyong Kastila nang mahigit 300 taon. Naging daan ito upang ang Katolisismo ang maging pangunahing pananampalataya. Sa gitna ng kapanahunang ito, ang Maynila ang naging sentro ng kalakalan ng kanluran sa Pasipiko na umuugnay sa Asya sa Acapulco sa Kaamerikahan gamit ang mga galyon ng Maynila. Nang magbigay daan ang ika-19 na dantaon sa ika-20, sumunod ang pagsiklab at tagumpay ng Himagsikang Pilipino."

tamil <- "அளவில், இந்தியாவின் வடமேற்கிலிருந்து ஏற்பட்ட ஆரிய இனக்குழுக்களின் உள்வரவாலும், ஓரளவுக்கு உள்ளூர் வாசிகளுடனான கலப்பினாலும் வேதகாலப் பண்பாடு உருவானதாக ஒரு கருத்து உண்டு. காலப்போக்கில் ஆரியரின் பண்பாடு, மொழி மற்றும் சமயம் என்பன இந்நாட்டில் மிக தலைமைத்துத்துவம் பெற்றவையாகின என்று இக்கருத்து கூறகிறது."

thai <- "พระบาทสมเด็จพระจุลจอมเกล้าเจ้าอยู่หัวทรงรวมศูนย์อำนาจ ตั้งสภาช่วยราชการ การเลิกทาสและไพร่อันเป็นการยกเลิกระบบแรงงานเกณฑ์ วิกฤตการณ์วังหน้าในปี 2417 ทำให้ความพยายามปฏิรูปต้องหยุดชะงัก ในคริสต์ทศวรรษ 1870–80 พระบาทสมเด็จพระจุลจอมเกล้าเจ้าอยู่หัวทรงใช้นโยบายผนวกหัวเมืองเหนือเข้าเป็นส่วนหนึ่งของราชอาณาจักร และต่อมาได้ขยายไปยังภาคตะวันออกเฉียงเหนือและภาตใต้  ในปี 2430 มีการตั้งกรมจำนวน 12 กรมซึ่งต่อมาเป็นกระทรวงต่าง ๆ"

turkish <- "Günümüzde Türkiye sınırları içinde kalan Anadolu Yarımadası, dünyanın en eski yerleşim bölgelerinden biridir. Çeşitli Eski Anadolu milletleri bölgede, Cilalı Taş Devri'nin başlangıcına ve Büyük İskender'in fethine kadar varlığını sürdürdü. Bu halkların çoğu Hint-Avrupa dil ailesinin bir kolu olarak kabul edilen Anadolu dillerini konuştu. Bazı bilim insanları Hint-Avrupa dillerinin, yine eski Anadolu dillerinden olan Hitit dili ve Luvi dilinden yayıldığını öne sürdü."

ukrainian <- "Сейсмічність України проявляється в західних, південно-західних і в південних районах, які розташовані поблизу потужного Середземноморсько-Альпійсько-Трансазійського сейсмогенного поясу планети, і де виділяються два основні сейсмічні регіони: Карпатський і Кримсько-Чорноморський. Значна частина території піддається впливам власних (місцевих) землетрусів і сильних підкорових землетрусів зони Вранча (Румунія)."

vietnamese <- "Lãnh thổ Việt Nam xuất hiện con người sinh sống từ thời đại đồ đá cũ. Lịch sử Việt Nam cổ đại bắt đầu với các nhà nước Văn Lang, Âu Lạc. Âu Lạc bị nhà Triệu từ phương Bắc thôn tính vào đầu thế kỷ thứ 2 TCN và sau đó là thời kỳ Bắc thuộc kéo dài hơn một thiên niên kỷ. Chế độ quân chủ độc lập được tái lập sau chiến thắng của Ngô Quyền trước nhà Nam Hán. Sự kiện này mở đường cho các triều đại độc lập kế tiếp và trong suốt giai đoạn lịch sử trung đại, quốc gia này tiếp tục giành chiến thắng trước các cuộc chiến tranh xâm lược từ phương Bắc và dần được mở rộng về phía nam."

welsh <- "Am gyfnod gwellodd sefyllfa'r Cymry. Diddymwyd y deddfau penyd a osodwyd ar y Cymry gan y Saeson ar ddechrau'r ganrif. Dan ei fab Harri VIII cyflwynwyd y Deddfau Uno a roddodd Cymru yn yr un system gyfreithiol a gweinyddol â Lloegr ond a waharddodd yr iaith Gymraeg o fywyd cyhoeddus y wlad. Ar yr un pryd newidiodd Cymru mewn cenhedlaeth neu ddwy o fod yn wlad Gatholig i fod yn wlad Brotestanaidd."

yiddish <- "ייִדישקײט אָדער ייִדנטום איז דער אינהאלט און צוזאמנשטעלונג פון דעם גלויבן און אויפירונג פונעם יידישן פאלק, וואס איז געבויט און שטאמט פון די תורה וואס דער אייבערשטער האט געגעבן פאר די יידן, און ווי שפעטער אפגעלערנט און ערקלערט אין תלמוד דורך די תנאים און אמוראים, און נאכהער צוזאמען גענומען דורך די פוסקים. יידישקייט איז דער פאראיינעגונג צווישן די יידישע קינדער און דעם אייבערשטן."

textcat(c(afrikaans, albanian, amharic, arabic, armenian, basque, belarusian, bosnian, breton, bulgarian, catalan, chinese, croatian, czech, danish, dutch, english, esperanto, estonian, finnish, french, frisian, georgian, german, greek, hebrew, hindi, hungarian, icelandic, indonesian, irish, italian, japanese, korean, latin, latvian, lithuanian, malay, manx, marathi, nepali, norwegian, persian, polish, portuguese, quechua, romanian, rumantsch, russian, sanskrit, scots, scotsGaelic, serbian, slovak, slovenian, spanish, swahili, swedish, tagalog, tamil, thai, turkish, ukrainian, vietnamese, welsh, yiddish))

textcat(c(afrikaans, albanian, amharic, arabic, armenian, basque, belarusian, bosnian, breton, bulgarian, catalan, chinese, croatian, czech, danish, dutch, english, esperanto, estonian, finnish, french, frisian, georgian, german, greek, hebrew, hindi, hungarian, icelandic, indonesian, irish, italian, japanese, korean, latin, latvian, lithuanian, malay, manx, marathi, nepali, norwegian, persian, polish, portuguese, quechua, romanian, rumantsch, russian, sanskrit, scots, scotsGaelic, serbian, slovak, slovenian, spanish, swahili, swedish, tagalog, tamil, thai, turkish, ukrainian, vietnamese, welsh, yiddish),p=textcat::TC_byte_profiles)